### ISSUE TITLE
Reach the first page of search results for relevant terms

### ISSUE THREAD

**Issue by Cantido** [InventorForgeMakerspace/website#5]
Phrases to use:
- [ ] Inventor Forge
- [ ] InventorForge
- [ ] Maker space Saint Charles MO
- [ ] Makerspace Saint Charles MO
- [ ] Maker space Saint Louis
- [ ] Makerspace Saint Louis
  - I think we need to be careful here based on our relationship with AR, this can be a goal but would be lower in the list (note: reordered and lowered on priorities, these should not be done with a goal of getting a higher search ranking than AR in STL searches)
- [ ] STEM Saint Charles MO

Reach out to Makespace lists, Arch reactor, other sites? to look for linking opportunities
I think we have hit all the popular makerspace lists. (ongoing maintenance only)

I believe George (@gfetters) might have already talked to AR about reciprocal page linking to bump up site ranking (follow up with George).

**Comment by gfetters** [comment]
I spoke to AR and they are good with it.  They run drupal so its a ton of
metatag stuff.  The person we need to give info to is Travis McGee.
